fix melpazoid warning and better github action for melpazoid

diff --git a/.github/workflows/melpazoid.yml b/.github/workflows/melpazoid.yml
--- a/.github/workflows/melpazoid.yml
+++ b/.github/workflows/melpazoid.yml
@@ -90,21 +90,28 @@ jobs:
           EXIST_OK: true
         run: |
           echo $GITHUB_REF
-          make -C ~/melpazoid |& tee output.log
-          make_exit=${PIPESTATUS[0]}
-          [ $make_exit -ne 0 ] && { echo "Make command failed, failing workflow"; exit 1; }
-          if grep -q "Warning" output.log ; then
+          make -C ~/melpazoid 2>&1 | tee output.log
+          MAKE_EXIT=$?
+          [ $MAKE_EXIT -ne 0 ] && { echo "Make command failed, failing workflow"; exit 1; }
+
+          # Strip ANSI codes for clean analysis
+          sed -i 's/\x1b\[[0-9;]*m//g' output.log
+
+          if grep "Warning" output.log | grep -q . ; then
             echo "Warnings detected, failing workflow" ; exit 1
           fi
-          if grep -q ': error: ' output.log ; then
-            echo "Error detected, failing workflow" ; exit 1
+          if grep ': error: ' output.log | grep -q . ; then
+            echo "Warnings detected, failing workflow" ; exit 1
           fi
-          if grep -q ' with [melpazoid]' output.log ; then
+
+          if grep -E ' with .?melpazoid' output.log | grep -q . ; then
+            grep -E ' with .?melpazoid' output.log
             echo "Melpazoid warning detected, failing workflow" ; exit 1
           fi
-          if grep -q ' with package-lint ' output.log ; then
+          if grep ' with package-lint ' output.log | grep -q . ; then
+            echo "Warnings detected, failing workflow" ; exit 1
+          fi
+          if grep ' with checkdoc ' output.log | grep -q . ; then
             echo "Checkdoc warning detected, failing workflow" ; exit 1
           fi
-          if grep -q ' with checkdoc ' output.log ; then
-            echo "Checkdoc warning detected, failing workflow" ; exit 1
-          fi
+           echo "normal"
